// media/chart.js draws the curves, so its Big-O maths has to stay in step with
// python/common/complexity.py. If these two ever disagree, the chart would
// draw a curve that is not the one the estimator chose.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { loadChartJs } = require('./helpers');

const I = loadChartJs();

/** The same argmin-of-log-error as _best_fit in python/common/complexity.py. */
function bestFit(sizes, values) {
    if (!values.some((v) => v > 0)) {
        return 'O(1)';
    }
    const floor = Math.max(...values) * 1e-9;
    const logs = values.map((v) => Math.log(Math.max(v, floor)));
    let best = 'O(1)';
    let bestErr = Infinity;
    for (const model of I.MODELS) {
        const basis = sizes.map((n) => Math.log(model.f(n)));
        const offset = logs.reduce((s, lv, i) => s + (lv - basis[i]), 0) / logs.length;
        const err = logs.reduce((s, lv, i) => s + (lv - (offset + basis[i])) ** 2, 0);
        if (err < bestErr) {
            best = model.name;
            bestErr = err;
        }
    }
    return best;
}

describe('growth models', () => {
    test('the same seven classes as MODELS in python/common/complexity.py', () => {
        assert.deepEqual(
            I.MODELS.map((m) => m.name),
            ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'O(n^2)', 'O(n^3)', 'O(2^n)']
        );
    });

    test('recovers the class from data generated by that class', () => {
        const sizes = [500, 1000, 2000, 4000, 8000];
        for (const model of I.MODELS) {
            if (model.name === 'O(2^n)') {
                continue;               // overflows well before n = 500
            }
            const values = sizes.map((n) => 3e-7 * model.f(n));
            assert.equal(bestFit(sizes, values), model.name, `misread ${model.name}`);
        }
    });
});

describe('fitScale', () => {
    test('lands the curve on data that follows the class exactly', () => {
        const sizes = [500, 1000, 2000, 4000, 8000];
        const model = I.MODELS.find((m) => m.name === 'O(n)');
        const values = sizes.map((n) => 4e-7 * n);
        const c = I.fitScale(sizes, values, model.f);
        for (let i = 0; i < sizes.length; i++) {
            const ratio = (c * model.f(sizes[i])) / values[i];
            assert.ok(Math.abs(ratio - 1) < 1e-9, `off by ${ratio}`);
        }
    });

    test('ignores zero and non-finite samples instead of returning NaN', () => {
        const model = I.MODELS.find((m) => m.name === 'O(n)');
        const c = I.fitScale([500, 1000, 2000], [0, 0.001, 0.002], model.f);
        assert.ok(Number.isFinite(c) && c > 0);
    });

    test('returns 0 when there is nothing usable', () => {
        assert.equal(I.fitScale([500], [0], I.MODELS[2].f), 0);
    });
});

describe('classesToDraw', () => {
    test('the fitted class first, then its neighbours', () => {
        assert.deepEqual(I.classesToDraw('O(n)'), ['O(n)', 'O(log n)', 'O(n log n)']);
    });
    test('no neighbour below the smallest class', () => {
        assert.deepEqual(I.classesToDraw('O(1)'), ['O(1)', 'O(log n)']);
    });
    test('never draws O(2^n) as context', () => {
        // Scaled to the data it leaves the plot immediately and tells you nothing.
        assert.deepEqual(I.classesToDraw('O(n^3)'), ['O(n^3)', 'O(n^2)']);
    });
});

describe('axis ticks', () => {
    test('log ticks subdivide a narrow range', () => {
        // Powers of ten alone would give only 1000 between 500 and 8000.
        assert.deepEqual(I.logTicks(500, 8000), [500, 1000, 2000, 5000]);
    });
    test('log ticks fall back to the ends when nothing fits', () => {
        assert.deepEqual(I.logTicks(1.04, 1.06), [1.04, 1.06]);
    });
    test('linear ticks are round numbers inside the range', () => {
        const ticks = I.niceTicks(0, 1.1, 4);
        assert.ok(ticks.length >= 3);
        assert.equal(ticks[0], 0);
        assert.ok(ticks.at(-1) <= 1.1 + 1e-9);
    });
    test('one decimal count per axis', () => {
        assert.equal(I.decimalsFor(0.9), 3);
        assert.equal(I.decimalsFor(9), 2);
        assert.equal(I.decimalsFor(90), 1);
        assert.equal(I.decimalsFor(900), 0);
    });
});

describe('default palette', () => {
    test('light and dark are chosen separately, not flipped', () => {
        assert.notEqual(I.DEFAULTS.light.measured, I.DEFAULTS.dark.measured);
        assert.notEqual(I.DEFAULTS.light.fitted, I.DEFAULTS.dark.fitted);
    });
    test('every default is a plain hex colour', () => {
        for (const mode of ['light', 'dark']) {
            for (const role of ['measured', 'fitted']) {
                assert.match(I.DEFAULTS[mode][role], /^#[0-9a-f]{6}$/);
            }
        }
    });
});
