#!/usr/bin/env python3
"""Regenerate the README progress block and PROGRESS.md from the solutions on
disk. Fills the region between <!-- stats:start --> and <!-- stats:end -->.

Safe and additive — run any time:  python scripts/gen_stats.py
"""
import pathlib
import re
import sys
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
import run  # noqa: E402  (import after sys.path tweak)

by_platform = defaultdict(lambda: defaultdict(int))  # platform -> short_lang -> count
langs_seen = set()
for s in run.discover():
    by_platform[s.platform][s.short_lang] += 1
    langs_seen.add(s.short_lang)

total = sum(sum(v.values()) for v in by_platform.values())
platforms = sorted(by_platform)
langs = sorted(langs_seen)

COLORS = {
    "leetcode": "orange", "codewars": "red", "adventofcode": "brightgreen",
    "hackerrank": "green", "codeforces": "blue", "others": "lightgrey",
}


def badge(platform, n):
    label = platform.replace("-", "--")
    return (f"![{platform}](https://img.shields.io/badge/"
            f"{label}-{n}%20solved-{COLORS.get(platform, 'informational')})")


def plural(n, word):
    return f"{n} {word}" + ("" if n == 1 else "s")


summary = " · ".join([plural(total, "solution"), plural(len(platforms), "platform"),
                      plural(len(langs), "language")])

if total:
    badges = " ".join(badge(p, sum(by_platform[p].values())) for p in platforms)
    head = "| Platform | " + " | ".join(langs) + " | Total |"
    sep = "|" + "|".join([" --- "] * (len(langs) + 2)) + "|"
    rows = []
    for p in platforms:
        cells = " | ".join(str(by_platform[p].get(l, 0)) for l in langs)
        rows.append(f"| {p} | {cells} | {sum(by_platform[p].values())} |")
    totals = " | ".join(str(sum(by_platform[p].get(l, 0) for p in platforms)) for l in langs)
    rows.append(f"| **Total** | {totals} | **{total}** |")
    table = "\n".join([head, sep, *rows])
    block = f"{badges}\n\n{summary}\n\n{table}"
else:
    block = "_No solutions yet — add one with_ `./run.sh new leetcode/easy/two_sum --lang py`."

readme = REPO / "README.md"
text = readme.read_text()
new, n = re.subn(r"(?s)(<!-- stats:start -->).*?(<!-- stats:end -->)",
                 lambda m: f"{m.group(1)}\n{block}\n{m.group(2)}", text)
if n == 0:
    sys.exit("error: stats markers (<!-- stats:start/end -->) not found in README.md")
readme.write_text(new)

(REPO / "PROGRESS.md").write_text(f"# Progress\n\n{block}\n\n_Generated by `scripts/gen_stats.py`._\n")
print(f"stats updated: {summary}")
